import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Menu from '../components/menu'
import Search from '../components/search'


export default function Home() {
  return (
    <div className={`${styles.container} ${styles.background}`}>
      <Head>
        <title>MasMas DashBoard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid grid-cols-5 gap-x-3.5">
        <div className="...">
          <Menu />
        </div>
        <div className="col-span-4 mr-6">
          <Search />
        </div>
      </div>
    </div>
  )
}
